[env]
	TERM = "xterm-256color"
[window]
	padding = { x = 4, y = 4 }
	decorations = "Buttonless"
	opacity = 0.85
	blur = true
	dimensions = { columns = 125, lines = 45 }

[font]
	normal = { family = "JetBrainsMono Nerd Font", style = "ExtraLight" }
	bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
	italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
	size = 14
[mouse]
    hide_when_typing = true
