##### COLOR SCHEME #####
# Default colors
# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = "#011423"
cursor = "#47FF9C"

[colors.primary]
background = "{{background}}"
foreground = "{{foreground}}"

[colors.normal]
black = "{{color0}}"
red = "{{color5}}"
green = "{{color2}}"
yellow = "{{color3}}"
blue = "{{color4}}"
magenta = "{{color5}}"
cyan = "{{color6}}"
white = "{{color7}}"

[colors.bright]
black = "{{color8}}"
red = "{{color5}}"
green = "{{color10}}"
yellow = "{{color11}}"
blue = "{{color12}}"
magenta = "{{color13}}"
cyan = "{{color14}}"
white = "{{color15}}"
