-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")

-- CENTER CURSOR --
-- vim.api.nvim_create_autocmd({ "CursorMoved", "CursorMovedI", "BufEnter" }, {
-- 	group = grp,
-- 	callback = function()
-- 		local win_h = vim.api.nvim_win_get_height(0)
-- 		local off = math.min(vim.o.scrolloff, math.floor(win_h / 2))
-- 		local dist = vim.fn.line("$") - vim.fn.line(".")
-- 		local rem = vim.fn.line("w$") - vim.fn.line("w0") + 1
-- 		if dist < off and win_h - rem + dist < off then
-- 			local view = vim.fn.winsaveview()
-- 			view.topline = view.topline + off - (win_h - rem + dist)
-- 			vim.fn.winrestview(view)
-- 		end
-- 	end,
-- })
