##### COLOR SCHEME #####
# Default colors
# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = "#011423"
cursor = "#47FF9C"

[colors.primary]
background = "#141219"
foreground = "#E4F7FB"

[colors.normal]
black = "#3C3942"
red = "#FDB979"
green = "#A486A7"
yellow = "#DAA970"
blue = "#D1AEC9"
magenta = "#FDB979"
cyan = "#B2E7F3"
white = "#D0EAF1"

[colors.bright]
black = "#92A4A8"
red = "#FDB979"
green = "#A486A7"
yellow = "#DAA970"
blue = "#D1AEC9"
magenta = "#FDB979"
cyan = "#B2E7F3"
white = "#D0EAF1"
