##### COLOR SCHEME #####
# Default colors
# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = "#011423"
cursor = "#47FF9C"

[colors.primary]
background = "#1F1E27"
foreground = "#F6F4F5"

[colors.normal]
black = "#46444E"
red = "#92D975"
green = "#7E9635"
yellow = "#85B357"
blue = "#C1CD85"
magenta = "#92D975"
cyan = "#E6E0E3"
white = "#EAE7E9"

[colors.bright]
black = "#A4A2A3"
red = "#92D975"
green = "#7E9635"
yellow = "#85B357"
blue = "#C1CD85"
magenta = "#92D975"
cyan = "#E6E0E3"
white = "#EAE7E9"
