##### COLOR SCHEME #####
# Default colors
# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = "#011423"
cursor = "#47FF9C"

[colors.primary]
background = "#151919"
foreground = "#C7E2F4"

[colors.normal]
black = "#3C4040"
red = "#639ACA"
green = "#093C65"
yellow = "#194F46"
blue = "#4685B6"
magenta = "#639ACA"
cyan = "#60ACDF"
white = "#A7CDE6"

[colors.bright]
black = "#7590A1"
red = "#639ACA"
green = "#093C65"
yellow = "#194F46"
blue = "#4685B6"
magenta = "#639ACA"
cyan = "#60ACDF"
white = "#A7CDE6"
