##### COLOR SCHEME #####
# Default colors
# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = "#011423"
cursor = "#47FF9C"

[colors.primary]
background = "#1B1A21"
foreground = "#B2FAFC"

[colors.normal]
black = "#424149"
red = "#33E4F1"
green = "#407DAA"
yellow = "#2089D4"
blue = "#2089D4"
magenta = "#33E4F1"
cyan = "#24F0F5"
white = "#89EFF2"

[colors.bright]
black = "#60A7A9"
red = "#33E4F1"
green = "#407DAA"
yellow = "#2089D4"
blue = "#2089D4"
magenta = "#33E4F1"
cyan = "#24F0F5"
white = "#89EFF2"
