##### COLOR SCHEME #####
# Default colors
# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = "#011423"
cursor = "#47FF9C"

[colors.primary]
background = "#1C1E20"
foreground = "#F6ECCE"

[colors.normal]
black = "#434546"
red = "#9AD890"
green = "#7AAEB4"
yellow = "#8BBE83"
blue = "#97CFDF"
magenta = "#9AD890"
cyan = "#E5C873"
white = "#EADBB0"

[colors.bright]
black = "#A4997B"
red = "#9AD890"
green = "#7AAEB4"
yellow = "#8BBE83"
blue = "#97CFDF"
magenta = "#9AD890"
cyan = "#E5C873"
white = "#EADBB0"
