##### COLOR SCHEME #####
# Default colors
# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = "#011423"
cursor = "#47FF9C"

[colors.primary]
background = "#151919"
foreground = "#BED4E6"

[colors.normal]
black = "#3C4040"
red = "#4685B6"
green = "#265069"
yellow = "#316283"
blue = "#3C749D"
magenta = "#4685B6"
cyan = "#4685B6"
white = "#9ABAD2"

[colors.bright]
black = "#6C8293"
red = "#4685B6"
green = "#265069"
yellow = "#316283"
blue = "#3C749D"
magenta = "#4685B6"
cyan = "#4685B6"
white = "#9ABAD2"
