[ui]
paginate = "never"
default-command = "log"

[user]
email = "jj.proofing240@passmail.com"
# email = "{some email}"
name = "DSPIRL"
# name = "{some name}"

[init]
defaultBranch = "main"

[core]
autocrlf = "input"
editor = "/usr/bin/nvim"
# editor = "{some editor path}"

[diff]
tool = "nvimdiff"

[difftool]
prompt = false

[signing]
# behavior = "own"
# backend = "gpg"
# key = "{some key}"

[git]
# sign-on-push = true
