[ui]
paginate = "never"
defualt-command = "log"

[user]
# email = "{some email}"
# name = "{some name}"

[init]
defaultBranch = "main"

[core]
autocrlf = "input"
# editor = "{some editor path}"

[diff]
tool = "nvimdiff"

[difftool]
prompt = false

[signing]
# behavior = "own"
# backend = "gpg"
# key = "{some key}"

[git]
# sign-on-push = true
